### ISSUE TITLE
popover location bug

### ISSUE THREAD

**Issue by austinmcdaniel** [predixdesignsystem/px-popover#21]
## Expected behavior and actual behavior:
Upgraded to the latest release (2.2.3) and noticed the popover location is broken - the popover appears in the top left-hand corner of the page. I noticed this in the px-login component. As of 2.1.3 the popover location is correct. I tested 2.1.3 (working), 2.2.0 (broken), 2.2.3 (broken).

## Steps to reproduce the problem:
Place the popover (or px-login which uses popover) on a web page and and click it. The popover shows up in the top left-hand side corner.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
>=2.2.0
chrome: 64.0.3282.167 (64 bit)
windows 7

## Screenshots (_optional, but very helpful_):
Working(2.1.3)
![image](https://user-images.githubusercontent.com/16106173/36502460-a8d164e8-170f-11e8-9824-deb70b836493.png)

Broken:
![image](https://user-images.githubusercontent.com/16106173/36502426-8d3b93ca-170f-11e8-8c6f-7ff885879832.png)

**Comment by randyaskin** [comment]
Ugh, will look into it again. 2.20 was supposed to fix another major bug (#16) whereby the position was broken in a different way.

**Comment by randyaskin** [comment]
I'm not seeing this in the popover or login components in isolation. Are you applying any styles directly on the px-login component? What can you tell me about the display, position, size constraints, etc of the parent container? Can you isolate it in a CodePen or something outside of your application?

**Comment by austinmcdaniel** [comment]
Sorry for the slow response on this.
I haven't been able to reproduce this in codepen. We are not applying any styles to the px-login component. From what I can tell the top and left CSS on the iron-dropdown aren't getting calculated correctly and both end up being 0 (thus placing the actual popup in the top left).

The parent container itself is not that interesting but above at different levels here are some of the settings:
width 100%; flex: 1; line-height: 1.3333; display: block
Fiddling with these in codepen didn't change the results.
